### ISSUE TITLE
justifikasi checkin/out

### ISSUE THREAD

**Issue by wiween** [mdridzuan80/emasa#1]
1. Bila isi untuk punch in dan tanda catatan sama dengan punch out - hanya punch in je ada.
Punch out masih kosong

**Comment by wiween** [comment]
<img width="1440" alt="Screenshot 2019-08-19 at 9 58 05 AM" src="https://user-images.githubusercontent.com/42923458/63245039-a96c3c00-c291-11e9-8f65-69830c16679b.png">

**Comment by mdridzuan80** [comment]
Fix

FYI duplicate dengan #2
