### ISSUE TITLE
justification - ralat

### ISSUE THREAD

**Issue by wiween** [mdridzuan80/emasa#2]
2. bila save justifikasi - masih keluar msg box ralat tu, dan skrin tak auto close
<img width="1440" alt="Screenshot 2019-08-19 at 9 58 35 AM" src="https://user-images.githubusercontent.com/42923458/63245134-e6383300-c291-11e9-8f1d-d7bc55787f0d.png">

**Comment by mdridzuan80** [comment]
cam ner nak reproduce masalah ni?

**Comment by mdridzuan80** [comment]
Fix

error kat databse index unique
