### ISSUE TITLE
laporan harian

### ISSUE THREAD

**Issue by wiween** [mdridzuan80/emasa#7]
laporan harian untuk hari semasa tidak  dapat diview. Jangan buat < tapi buat <= tarikh hari ini

**Comment by mdridzuan80** [comment]
Ok jer laporan ni.

![Screenshot 2019-08-23 at 5 18 04 AM](https://user-images.githubusercontent.com/13112163/63550542-7a8de880-c565-11e9-8148-2d0d3b77d4ab.png)

**Comment by wiween** [comment]
<img width="1440" alt="Screenshot 2019-08-23 at 9 12 29 AM" src="https://user-images.githubusercontent.com/42923458/63559858-41b23b80-c586-11e9-9fa0-4f514bb479ea.png">

i x dapat? bila pepagi
